# Generated by Django 4.0.6 on 2023-03-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_contenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='age_limit',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Kids', 'Kids')], max_length=10, null=True),
        ),
    ]
