# Generated by Django 4.0.6 on 2023-06-12 15:02

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_video_age_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='flyers',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='flyers'),
        ),
    ]
